player_database=[
    (2001,"Picard","avatar_picard2.png"),
    (2002,"Orly","avatar_orly.png"),
    (2003,"GrandMa","avatar_grandma.png"),
    (2004,"SeriousCat","avatar_serious_cat.png"),
    (2005,"MickeyMouse","avatar_mrvn.png"),
    (2006,"Goldsmith","avatar_goldsmith.png"),

    (2017,"LumberJack","avatar_lumberjack.png"),
    (2008,"PontiusPilatus","avatar_pontius_pilatus3.png"),
    (2012,"God","avatar_god.png"),
    (2025,"BriansMom","avatar_brians_mom.png"),
    (2011,"FrenchKnight","avatar_french_knight.png"),
    (2031,"TheOrganist","avatar_the_organist.png"),

    (2042,"JesusQuintana","avatar_jesus_quintana.png"),
    (2013,"DarkHelmet","avatar_dark_helmet.png"),
    (2026,"DottyMatrix","avatar_dotty_matrix.png"),
    (2020,"Barf","avatar_barf2.png"),
    (2040,"Garth Elgar","avatar_garth_elgar.png"),
    (2041,"Doc Brown","avatar_doc_brown.png"),

    (3000,"ElaineMarley","avatar_elaine_marley.png"),
    (3003,"LeChuck","avatar_le_chuck.png"),
    (3002,"HermanToothrot","avatar_herman_toothrot.png"),
    (3001,"Guybrush","avatar_guybrush_threepwood.png"),
    (3005,"3HeadedMonkey","avatar_three_headed_monkey.png"),
    (3004,"StanStanman","avatar_stan_s_stanman.png"),

    (2075,"Dr.Fred","avatar_dr_fred.png"),
    (2071,"PurpleTentacle","avatar_purple_tentacle.png"),
    (2073,"Bernhard","avatar_bernhard.png"),
    (2072,"Hoagie","avatar_hoagie.png"),
    (2074,"Laverne","avatar_laverne_incognito.png"),
    (2070,"GreenTentacle","avatar_green_tentacle.png"),

    (2014,"BrainSurgent","avatar_brain_surgent.png"),
    (2015,"JohnCleese","avatar_john_cleese.png"),
    #(2019,"DennisMoore1","avatar_dennis_moore1.png"),
    (2018,"WalterSobchak","avatar_walter_sobchak.png"),
    (2019,"TheRealData","avatar_the_real_data.png"),
    (2016,"PontiusPilatus","avatar_pontius_pilatus1.png"),
    #(2022,"Terminator","avatar_terminator.png"),
    #(2023,"Picard1","avatar_picard1.png"),

    (2021,"Bender","avatar_bender.png"),
    (2022,"Loretta","avatar_loretta.png"),
    (2023,"BiggusDickus","avatar_biggus_dickus.png"),
    (2024,"Tim","avatar_tim2.png"),
    (2009,"NudgeNudge","avatar_nudge_nudge.png"),
    (2027,"AdmiralBenson","avatar_admiral_benson.png"),
    (2028,"PontiusPilatus","avatar_pontius_pilatus2.png"),
    (2029,"Hal9001","avatar_hal_9001.png"),
    (2030,"TheDude1","avatar_the_dude1.png"),
    (2032,"Tim1","avatar_tim1.png"),
    #(2037,"AliceCooper1","avatar_alice_cooper1.png"),
    (2033,"AliceCooper","avatar_alice_cooper2.png"),
    (2034,"MrStoat","avatar_mr_stoat.png"),
    (2035,"Barf","avatar_barf1.png"),
    (2036,"TheDude2","avatar_the_dude2.png"),
    (2037,"Potr1pper","avatar_potr1pper.png"),
    (2038,"Brian","avatar_brian.png"),
    (2039,"Spanish Inq","avatar_spanish_inq.png"),
    (2007,"DennisMoore","avatar_dennis_moore2.png"),
    (2010,"Supermax","avatar_supermax.png")
]
